'use client';

import Link from 'next/link';
import { FormEvent, Fragment, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { LocationSelects } from '../../../components/locations/LocationSelects';
import { apiUrl } from '../../../lib/api';
import { getSession } from '../../../lib/auth';
import { establishmentLabels, EstablishmentType } from '../../../lib/public-restaurants';

type Owner = { id: string; name: string; email: string };
type StoreUser = Owner & { role: 'RESTAURANT_ADMIN' | 'EMPLOYEE'; active: boolean };
type Restaurant = { _id: string; name: string; slug: string; tradeName?: string; city?: string; state?: string; establishmentType: EstablishmentType; open: boolean; blocked: boolean; owner?: Owner };
type Form = { name: string; slug: string; tradeName: string; establishmentType: EstablishmentType; cnpj: string; email: string; phone: string; whatsapp: string; instagram: string; address: string; state: string; city: string; description: string; logoUrl: string; bannerUrl: string };
type OwnerForm = { name: string; email: string; phone: string; password: string; confirmPassword: string };
const blank: Form = { name: '', slug: '', tradeName: '', establishmentType: 'RESTAURANT', cnpj: '', email: '', phone: '', whatsapp: '', instagram: '', address: '', state: '', city: '', description: '', logoUrl: '', bannerUrl: '' };
const blankOwner: OwnerForm = { name: '', email: '', phone: '', password: '', confirmPassword: '' };

export default function AdminRestaurantsPage() {
  const router = useRouter();
  const [items, setItems] = useState<Restaurant[]>([]); const [search, setSearch] = useState(''); const [type, setType] = useState(''); const [status, setStatus] = useState('all');
  const [message, setMessage] = useState('Carregando…'); const [form, setForm] = useState<Form>(blank); const [owner, setOwner] = useState<OwnerForm>(blankOwner); const [sameEmail, setSameEmail] = useState(false);
  const [editing, setEditing] = useState<string>(); const [showForm, setShowForm] = useState(false); const [submitting, setSubmitting] = useState(false); const [success, setSuccess] = useState<{ establishment: string; owner: string; email: string }>();
  const [addingOwner, setAddingOwner] = useState<Restaurant>(); const [expanded, setExpanded] = useState<string>(); const [storeUsers, setStoreUsers] = useState<Record<string, StoreUser[]>>({});

  async function load() { const session = getSession(); if (!session || session.user.role !== 'SUPER_ADMIN') { router.replace('/login?returnTo=/admin/restaurantes'); return; } try { const response = await fetch(apiUrl('/restaurants'), { headers: { Authorization: `Bearer ${session.accessToken}` } }); if (!response.ok) throw new Error(); setItems(await response.json() as Restaurant[]); setMessage(''); } catch { setMessage('Não foi possível carregar os estabelecimentos.'); } }
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => items.filter((item) => (!search || `${item.name} ${item.slug} ${item.tradeName ?? ''}`.toLowerCase().includes(search.toLowerCase())) && (!type || item.establishmentType === type) && (status === 'all' || (status === 'blocked' ? item.blocked : status === 'active' ? !item.blocked : status === 'open' ? item.open : !item.open))), [items, search, type, status]);
  function errorMessage(result: { message?: string | string[] } | null, fallback: string) { return Array.isArray(result?.message) ? result.message[0] : result?.message ?? fallback; }
  async function submit(event: FormEvent) {
    event.preventDefault(); if (submitting) return; const session = getSession(); if (!session) return;
    if (!editing && owner.password !== owner.confirmPassword) { setMessage('As senhas não coincidem.'); return; }
    setSubmitting(true); setMessage(''); setSuccess(undefined);
    const establishment = Object.fromEntries(Object.entries(form).filter(([, value]) => value !== ''));
    const body = editing ? establishment : { establishment, owner: { name: owner.name, email: owner.email, phone: owner.phone || undefined, password: owner.password } };
    try {
      const response = await fetch(apiUrl(editing ? `/restaurants/${editing}` : '/restaurants/with-admin'), { method: editing ? 'PATCH' : 'POST', headers: { Authorization: `Bearer ${session.accessToken}`, 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
      const result = await response.json().catch(() => null) as { message?: string | string[]; establishment?: { name: string }; owner?: Owner } | null;
      if (!response.ok) { setMessage(errorMessage(result, 'Não foi possível salvar o estabelecimento.')); return; }
      if (!editing && result?.establishment && result.owner) { setSuccess({ establishment: result.establishment.name, owner: result.owner.name, email: result.owner.email }); setMessage('Estabelecimento e usuário criados com sucesso.'); }
      setForm(blank); setOwner(blankOwner); setSameEmail(false); setEditing(undefined); setShowForm(false); await load();
    } finally { setSubmitting(false); }
  }
  async function addOwner(event: FormEvent) {
    event.preventDefault(); if (!addingOwner || submitting) return; if (owner.password !== owner.confirmPassword) { setMessage('As senhas não coincidem.'); return; } const session = getSession(); if (!session) return; setSubmitting(true);
    try { const response = await fetch(apiUrl(`/restaurants/${addingOwner._id}/owners`), { method: 'POST', headers: { Authorization: `Bearer ${session.accessToken}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ name: owner.name, email: owner.email, phone: owner.phone || undefined, password: owner.password }) }); const result = await response.json().catch(() => null) as { message?: string | string[] } | null; if (!response.ok) { setMessage(errorMessage(result, 'Não foi possível adicionar o lojista.')); return; } setMessage('Lojista adicionado com sucesso.'); setAddingOwner(undefined); setOwner(blankOwner); await load(); } finally { setSubmitting(false); }
  }
  async function showUsers(item: Restaurant) { if (expanded === item._id) { setExpanded(undefined); return; } const session = getSession(); if (!session) return; const response = await fetch(apiUrl(`/restaurants/${item._id}/users`), { headers: { Authorization: `Bearer ${session.accessToken}` } }); const users = response.ok ? await response.json() as StoreUser[] : []; if (!response.ok) setMessage('Não foi possível carregar os usuários do estabelecimento.'); setStoreUsers((current) => ({ ...current, [item._id]: users })); setExpanded(item._id); }
  async function toggle(item: Restaurant) { const session = getSession(); if (!session) return; const response = await fetch(apiUrl(`/restaurants/${item._id}`), { method: 'PATCH', headers: { Authorization: `Bearer ${session.accessToken}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ blocked: !item.blocked }) }); if (response.ok) setItems((current) => current.map((value) => value._id === item._id ? { ...value, blocked: !value.blocked } : value)); else setMessage('Não foi possível atualizar o estabelecimento.'); }
  function edit(item: Restaurant) { setForm({ ...blank, name: item.name, slug: item.slug, tradeName: item.tradeName ?? '', establishmentType: item.establishmentType ?? 'RESTAURANT', city: item.city ?? '', state: item.state ?? '' }); setEditing(item._id); setShowForm(true); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  const ownerFields = (includeSameEmail: boolean) => <div className="grid gap-x-4 gap-y-3 md:grid-cols-2"><label className="font-bold">Nome do responsável *<input required className="field" value={owner.name} onChange={(e) => setOwner({ ...owner, name: e.target.value })} /></label><label className="font-bold">E-mail de acesso *<input required type="email" className="field" value={owner.email} onChange={(e) => { setSameEmail(false); setOwner({ ...owner, email: e.target.value }); }} /></label><label className="font-bold">Telefone<input className="field" value={owner.phone} onChange={(e) => setOwner({ ...owner, phone: e.target.value })} /></label><span />{includeSameEmail && <label className="flex items-center gap-2 font-semibold md:col-span-2"><input type="checkbox" checked={sameEmail} onChange={(e) => { setSameEmail(e.target.checked); setOwner({ ...owner, email: e.target.checked ? form.email : '' }); }} /> Usar o mesmo e-mail do estabelecimento</label>}<label className="font-bold">Senha *<input required minLength={8} type="password" className="field" value={owner.password} onChange={(e) => setOwner({ ...owner, password: e.target.value })} /></label><label className="font-bold">Confirmar senha *<input required minLength={8} type="password" className="field" value={owner.confirmPassword} onChange={(e) => setOwner({ ...owner, confirmPassword: e.target.value })} /></label></div>;

  return <main className="min-h-screen p-4 sm:p-8"><section className="mx-auto max-w-7xl"><header className="flex flex-wrap items-center justify-between gap-4"><div><Link href="/admin" className="text-sm font-bold text-stone-500">← Painel</Link><h1 className="mt-2 text-3xl font-black">Estabelecimentos</h1><p className="mt-1 text-stone-500">Restaurantes, farmácias, roupas e outras lojas.</p></div><button className="rounded-xl bg-ink px-5 py-3 font-bold text-white" onClick={() => { setForm(blank); setOwner(blankOwner); setEditing(undefined); setShowForm(!showForm); }}>{showForm ? 'Cancelar' : 'Novo estabelecimento'}</button></header>
    {showForm && <form onSubmit={submit} className="mt-7 rounded-2xl bg-white p-5 shadow-sm"><h2 className="border-b pb-3 text-xl font-black">DADOS DO ESTABELECIMENTO</h2><div className="mt-5 grid gap-x-4 gap-y-3 md:grid-cols-2">{([['name','Nome *'],['tradeName','Nome fantasia'],['slug','Slug *'],['cnpj','CNPJ'],['email','E-mail'],['phone','Telefone'],['whatsapp','WhatsApp'],['instagram','Instagram'],['address','Endereço'],['logoUrl','URL do logo'],['bannerUrl','URL do banner']] as Array<[keyof Form,string]>).map(([key,label]) => <label key={key} className="font-bold">{label}<input required={key === 'name' || key === 'slug'} type={key === 'email' ? 'email' : 'text'} className="field" value={form[key]} onChange={(e) => { const value = e.target.value; setForm({ ...form, [key]: value }); if (key === 'email' && sameEmail) setOwner({ ...owner, email: value }); }} /></label>)}<label className="font-bold">Tipo do estabelecimento *<select required className="field" value={form.establishmentType} onChange={(e) => setForm({ ...form, establishmentType: e.target.value as EstablishmentType })}>{Object.entries(establishmentLabels).map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select></label><LocationSelects state={form.state} city={form.city} onState={(state) => setForm((current) => ({ ...current, state, city: '' }))} onCity={(city) => setForm((current) => ({ ...current, city }))} /><label className="font-bold md:col-span-2">Descrição<textarea className="field min-h-24" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label></div>{!editing && <section className="mt-8 border-t pt-6"><h2 className="mb-5 text-xl font-black">DADOS DE ACESSO DO LOJISTA</h2>{ownerFields(true)}</section>}<button disabled={submitting} className="mt-6 rounded-xl bg-ink px-6 py-3 font-bold text-white disabled:cursor-not-allowed disabled:opacity-60">{submitting ? 'Cadastrando...' : editing ? 'Salvar estabelecimento' : 'CADASTRAR ESTABELECIMENTO E USUÁRIO'}</button></form>}
    {success && <div className="mt-6 rounded-2xl border border-green-200 bg-green-50 p-5"><p className="font-black text-green-800">Estabelecimento e usuário criados com sucesso.</p><p className="mt-2"><b>Estabelecimento:</b> {success.establishment}</p><p><b>Lojista:</b> {success.owner} — {success.email}</p></div>}
    <div className="mt-7 grid gap-3 rounded-2xl bg-white p-4 shadow-sm md:grid-cols-3"><input className="field !mt-0" placeholder="Buscar nome ou slug" value={search} onChange={(e) => setSearch(e.target.value)} /><select className="field !mt-0" value={type} onChange={(e) => setType(e.target.value)}><option value="">Todos os tipos</option>{Object.entries(establishmentLabels).map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select><select className="field !mt-0" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">Todos os status</option><option value="active">Ativos</option><option value="blocked">Bloqueados</option><option value="open">Abertos</option><option value="closed">Fechados</option></select></div>{message && <p className="mt-6 rounded-xl bg-white p-4">{message}</p>}
    <div className="mt-5 overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="border-b bg-stone-50 text-xs uppercase text-stone-500"><tr>{['Nome','Tipo','Cidade / UF','Funcionamento','Status','Lojista responsável','E-mail do lojista','Ações'].map((label) => <th className="p-4" key={label}>{label}</th>)}</tr></thead><tbody>{filtered.map((item) => <Fragment key={item._id}><tr className="border-b"><td className="p-4 font-bold">{item.tradeName || item.name}</td><td className="p-4">{establishmentLabels[item.establishmentType ?? 'RESTAURANT']}</td><td className="p-4">{item.city || '—'} {item.state && `/ ${item.state}`}</td><td className="p-4">{item.open ? 'Aberto' : 'Fechado'}</td><td className="p-4">{item.blocked ? 'Bloqueado' : 'Ativo'}</td><td className="p-4">{item.owner?.name ?? '—'}</td><td className="p-4">{item.owner?.email ?? '—'}</td><td className="p-4"><div className="flex flex-wrap gap-3"><button className="font-bold underline" onClick={() => edit(item)}>Editar</button><button className="font-bold underline" onClick={() => void toggle(item)}>{item.blocked ? 'Desbloquear' : 'Bloquear'}</button><button className="font-bold underline" onClick={() => { setOwner(blankOwner); setAddingOwner(item); }}>Adicionar lojista</button><button className="font-bold underline" onClick={() => void showUsers(item)}>Usuários</button></div></td></tr>{expanded === item._id && <tr><td colSpan={8} className="bg-stone-50 p-4"><h3 className="font-black">Usuários do estabelecimento</h3><div className="mt-2 grid grid-cols-4 gap-2 text-sm font-bold"><span>Nome</span><span>E-mail</span><span>Role</span><span>Ativo/Inativo</span></div>{storeUsers[item._id]?.map((user) => <div key={user.id} className="grid grid-cols-4 gap-2 border-t py-2"><span>{user.name}</span><span>{user.email}</span><span>{user.role}</span><span>{user.active ? 'Ativo' : 'Inativo'}</span></div>)}</td></tr>}</Fragment>)}</tbody></table>{!message && filtered.length === 0 && <p className="p-8 text-center text-stone-500">Nenhum estabelecimento corresponde aos filtros.</p>}</div>
    {addingOwner && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={addOwner} className="w-full max-w-2xl rounded-2xl bg-white p-6"><div className="flex justify-between"><div><h2 className="text-xl font-black">Adicionar lojista</h2><p className="text-stone-500">{addingOwner.tradeName || addingOwner.name}</p></div><button type="button" className="font-bold" onClick={() => setAddingOwner(undefined)}>✕</button></div><div className="mt-5">{ownerFields(false)}</div><button disabled={submitting} className="mt-6 rounded-xl bg-ink px-6 py-3 font-bold text-white disabled:opacity-60">{submitting ? 'Cadastrando...' : 'Adicionar lojista'}</button></form></div>}
  </section></main>;
}
