'use client';

import { useEffect, useMemo, useState } from 'react';
import { useEmpresa } from '../../../components/empresa/EmpresaContext';
import { apiUrl } from '../../../lib/api';
import { getSession } from '../../../lib/auth';

type Estimate = { period: string; revenueCents: number; completedOrderCount: number; amountCents: number; tier: { minRevenueCents: number; maxRevenueCents: number|null; amountCents: number }; plan: { name: string } };
type Invoice = { _id: string; period: string; revenueCents?: number; completedOrderCount?: number; amountCents: number; status: 'OPEN'|'PAID'|'OVERDUE'|'WAIVED'|'CANCELLED'; dueDate?: string; pricingSnapshot?: { tier?: { minRevenueCents?: number; maxRevenueCents?: number|null; amountCents?: number } } };
type Response = { period: string; estimate: Estimate; invoices: Invoice[]; paymentSettings?: { pixReceiverName?: string; pixKey?: string } };
const money = (cents = 0) => (cents/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const currentPeriod = () => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`; };
const labelPeriod = (period:string) => { const [y,m]=period.split('-').map(Number); return new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(y,m-1,1)); };
const statusLabel:Record<string,string>={OPEN:'Pendente',PAID:'Pago',OVERDUE:'Vencido',WAIVED:'Isento',CANCELLED:'Cancelado'};
const statusTone:Record<string,string>={OPEN:'bg-amber-50 text-amber-800',PAID:'bg-emerald-50 text-emerald-800',OVERDUE:'bg-red-50 text-red-700',WAIVED:'bg-blue-50 text-blue-700',CANCELLED:'bg-stone-100 text-stone-600'};

export default function Page(){
  const { request } = useEmpresa();
  const [data,setData]=useState<Response>();
  const [message,setMessage]=useState('');
  const [selected,setSelected]=useState<Invoice>();
  const [pdfLoading,setPdfLoading]=useState('');
  const period=useMemo(currentPeriod,[]);
  useEffect(()=>{request<Response>(`/billing/me?period=${period}`,{cache:'no-store'}).then(setData).catch((e)=>setMessage(e instanceof Error?e.message:'Não foi possível carregar sua assinatura.'));},[period,request]);
  async function downloadInvoicePdf(invoice: Invoice) {
    setPdfLoading(invoice._id); setMessage('');
    try {
      const response = await fetch(apiUrl(`/billing/me/invoices/${invoice._id}/pdf`), { headers: { Authorization: `Bearer ${getSession()?.accessToken}` }, cache: 'no-store' });
      if (!response.ok) throw new Error('Não foi possível gerar o PDF da cobrança.');
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const anchor = document.createElement('a'); anchor.href = url; anchor.download = `menu-flow-mensalidade-${invoice.period}.pdf`; anchor.click(); URL.revokeObjectURL(url);
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível gerar o PDF da cobrança.'); }
    finally { setPdfLoading(''); }
  }
  if(!data) return <section className="mx-auto max-w-6xl"><div className="h-56 animate-pulse rounded-[30px] bg-stone-200" />{message&&<p className="mt-4 rounded-2xl border bg-white p-4">{message}</p>}</section>;
  const estimate=data.estimate;
  const max=estimate.tier.maxRevenueCents;
  const next=max===null?null:max-estimate.revenueCents+1;
  const progress=max===null?100:Math.min(100,Math.max(0,(estimate.revenueCents/Math.max(1,max))*100));
  return <section className="mx-auto max-w-6xl space-y-6">
    <header className="overflow-hidden rounded-[32px] bg-gradient-to-r from-ink via-[#6f1c21] to-[#8f242a] p-6 text-white shadow-xl sm:p-7"><p className="text-[10px] font-black uppercase tracking-[.22em] text-lime">Menu Flow</p><h1 className="mt-2 text-3xl font-black">Minha assinatura</h1><p className="mt-2 max-w-2xl text-sm text-white/75">No dia 1º de cada mês sua mensalidade é gerada automaticamente com base no faturamento do mês anterior.</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><Card label="Faturamento deste mês" value={money(estimate.revenueCents)} /><Card label="Mensalidade estimada" value={money(estimate.amountCents)} /><Card label="Vendas consideradas" value={String(estimate.completedOrderCount)} /></div></header>
    <section className="rounded-[28px] border bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.15em] text-primary">Faixa atual · {labelPeriod(period)}</p><h2 className="mt-2 text-2xl font-black">{max===null?`Acima de ${money(estimate.tier.minRevenueCents-1)}`:`${money(estimate.tier.minRevenueCents)} a ${money(max)}`}</h2><p className="mt-1 text-sm text-stone-500">Estimativa enquanto o mês ainda está aberto. A cobrança é fechada com base no mês completo.</p></div><strong className="rounded-2xl bg-primary/10 px-5 py-3 text-2xl font-black text-primary">{money(estimate.amountCents)}</strong></div><div className="mt-5 h-3 overflow-hidden rounded-full bg-stone-100"><div className="h-full rounded-full bg-primary" style={{width:`${progress}%`}} /></div><div className="mt-2 flex justify-between gap-3 text-xs font-bold text-stone-500"><span>{money(estimate.revenueCents)}</span><span>{next===null?'Faixa máxima':`${money(Math.max(0,next))} até a próxima faixa`}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Tier label="Até R$ 1.000" price="R$ 49,90" /><Tier label="R$ 1.000,01 a R$ 3.500" price="R$ 69,90" /><Tier label="Acima de R$ 3.500" price="R$ 129,90" /></div><p className="mt-4 rounded-2xl bg-background p-4 text-sm text-stone-600"><b>O que entra:</b> produtos vendidos menos descontos. Taxa de entrega, taxa de serviço do garçom e pedidos cancelados não entram na faixa.</p></section>

    {data.invoices.some((invoice)=>invoice.status==='OPEN'||invoice.status==='OVERDUE') && <section className="rounded-[28px] border bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.15em] text-primary">Pagamento</p><h2 className="mt-2 text-xl font-black">Mensalidade pendente</h2><p className="mt-1 text-sm text-stone-500">A cobrança mensal fica disponível aqui com todos os dados e o PDF oficial do Menu Flow.</p></div><div className="rounded-2xl bg-background p-4 text-sm"><p><b>Favorecido:</b> {data.paymentSettings?.pixReceiverName || 'Não informado'}</p><p className="mt-1 break-all"><b>Chave PIX:</b> {data.paymentSettings?.pixKey || 'Não informada'}</p></div></div></section>}
    <section><div className="mb-3"><h2 className="text-xl font-black">Histórico de mensalidades</h2><p className="text-sm text-stone-500">Valores já fechados não mudam quando as faixas futuras forem atualizadas.</p></div><div className="grid gap-3">{data.invoices.map((invoice)=><article key={invoice._id} className="grid gap-3 rounded-[24px] border bg-white p-5 shadow-sm lg:grid-cols-[1.15fr_.8fr_.8fr_.8fr_auto] lg:items-center"><div><span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-black ${statusTone[invoice.status]}`}>{statusLabel[invoice.status]}</span><h3 className="mt-2 font-black capitalize">Referência: {labelPeriod(invoice.period)}</h3><p className="mt-1 text-xs text-stone-500">Cobrança gerada automaticamente no ciclo mensal.</p></div><Metric label="Faturamento considerado" value={money(invoice.revenueCents??0)} /><Metric label="Vendas consideradas" value={String(invoice.completedOrderCount??0)} /><Metric label="Mensalidade" value={money(invoice.amountCents)} /><div className="flex flex-wrap gap-2 lg:justify-end"><button type="button" onClick={()=>setSelected(invoice)} className="rounded-xl border px-3 py-2 text-xs font-black">Ver cobrança</button><button type="button" disabled={pdfLoading===invoice._id} onClick={()=>void downloadInvoicePdf(invoice)} className="rounded-xl bg-ink px-3 py-2 text-xs font-black text-white disabled:opacity-50">{pdfLoading===invoice._id?'Gerando…':'📄 PDF'}</button></div></article>)}{!data.invoices.length&&<div className="rounded-2xl border border-dashed bg-white p-8 text-center text-sm text-stone-500">Nenhuma mensalidade fechada ainda.</div>}</div></section>
    {message&&<div className="rounded-2xl border bg-white p-4 text-sm font-bold">{message}</div>}
    {selected&&<div className="fixed inset-0 z-[90] overflow-y-auto bg-black/60 p-3 sm:p-6" onClick={()=>setSelected(undefined)}><div className="mx-auto my-8 max-w-2xl rounded-[28px] bg-white p-5 shadow-2xl sm:p-6" onClick={(e)=>e.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-primary">Cobrança Menu Flow</p><h2 className="mt-1 text-2xl font-black">{labelPeriod(selected.period)}</h2><span className={`mt-2 inline-flex rounded-full px-2.5 py-1 text-[10px] font-black ${statusTone[selected.status]}`}>{statusLabel[selected.status]}</span></div><button type="button" onClick={()=>setSelected(undefined)} className="grid h-10 w-10 place-items-center rounded-full bg-stone-100 font-black">×</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><MetricCard label="Faturamento considerado" value={money(selected.revenueCents??0)} /><MetricCard label="Mensalidade" value={money(selected.amountCents)} /><MetricCard label="Vendas consideradas" value={String(selected.completedOrderCount??0)} /><MetricCard label="Vencimento" value={selected.dueDate?new Date(selected.dueDate).toLocaleDateString('pt-BR'):'—'} /></div><div className="mt-4 rounded-2xl bg-background p-4 text-sm text-stone-600"><p><b>Base da cobrança:</b> produtos vendidos menos descontos.</p><p className="mt-1">Taxa de entrega, taxa de serviço do garçom e pedidos cancelados não entram na faixa.</p></div>{(selected.status==='OPEN'||selected.status==='OVERDUE')&&<div className="mt-4 rounded-2xl border p-4 text-sm"><p><b>Favorecido:</b> {data.paymentSettings?.pixReceiverName || 'Não informado'}</p><p className="mt-1 break-all"><b>Chave PIX:</b> {data.paymentSettings?.pixKey || 'Não informada'}</p></div>}<button type="button" disabled={pdfLoading===selected._id} onClick={()=>void downloadInvoicePdf(selected)} className="mt-5 w-full rounded-2xl bg-ink px-5 py-3 font-black text-white disabled:opacity-50">{pdfLoading===selected._id?'Gerando PDF…':'📄 Baixar cobrança em PDF'}</button></div></div>}
  </section>;
}
function Card({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-white/70">{label}</p><strong className="mt-1 block text-xl font-black">{value}</strong></div>}
function Tier({label,price}:{label:string;price:string}){return <div className="rounded-2xl border bg-background/50 p-4"><p className="text-xs font-bold text-stone-500">{label}</p><strong className="mt-1 block text-lg font-black">{price}</strong></div>}
function Metric({label,value}:{label:string;value:string}){return <div><p className="text-[10px] font-black uppercase tracking-[.12em] text-stone-400">{label}</p><strong className="mt-1 block">{value}</strong></div>}
function MetricCard({label,value}:{label:string;value:string}){return <div className="rounded-2xl border bg-background/50 p-4"><p className="text-[10px] font-black uppercase tracking-[.12em] text-stone-400">{label}</p><strong className="mt-1 block text-lg">{value}</strong></div>}
