'use client';
import { FormEvent, useCallback, useEffect, useRef, useState } from 'react';
import { useEmpresa } from '../../../components/empresa/EmpresaContext';
type Settings = { connected: boolean; serverReady: boolean; enabled: boolean; displayPhone: string; greeting: string; deliveryText: string; handoffText: string; menuUrl: string; lastError: string; lastReceivedAt?: string };
type Conversation = { _id: string; customerPhone: string; customerName: string; human: boolean; optedOut: boolean; lastText: string; lastIncomingAt?: string };
type Message = { _id: string; direction: string; text: string; status: string; error?: string; createdAt: string };
type History = { conversation: Conversation; canReply: boolean; messages: Message[] };
const field = 'mt-1 w-full rounded-xl border border-stone-300 bg-white p-3 text-sm text-stone-900 focus:border-emerald-600 focus:outline-none';
const button = 'rounded-xl bg-emerald-700 px-4 py-2.5 font-bold text-white disabled:cursor-not-allowed disabled:opacity-50';
const statusLabels: Record<string,string> = { pending:'Na fila', sending:'Enviando', sent:'Enviada à Meta', delivered:'Entregue', read:'Lida', failed:'Falhou', unknown:'Envio sem confirmação', cancelled:'Cancelada', received:'Recebida' };
export default function WhatsappPage() {
  const { request } = useEmpresa();
  const [settings,setSettings] = useState<Settings|null>(null); const [list,setList] = useState<Conversation[]>([]);
  const [selected,setSelected] = useState(''); const [history,setHistory] = useState<History|null>(null);
  const [reply,setReply] = useState(''); const [error,setError] = useState(''); const [notice,setNotice] = useState('');
  const [busy,setBusy] = useState(false); const [tab,setTab] = useState<'inbox'|'settings'>('inbox');
  const requestId = useRef(''); const active = useRef('');
  const loadList = useCallback(async () => { setList(await request<Conversation[]>('/whatsapp/conversations',{cache:'no-store'})); },[request]);
  useEffect(() => { let cancelled=false; void request<Settings>('/whatsapp/settings',{cache:'no-store'}).then(v=>{if(!cancelled)setSettings(v)}).catch(e=>{if(!cancelled)setError(e.message)}); return()=>{cancelled=true}; },[request]);
  useEffect(() => { void loadList().catch(e=>setError(e.message)); const timer=setInterval(()=>{void loadList().catch(e=>setError(e.message))},10000);return()=>clearInterval(timer); },[loadList]);
  useEffect(() => {
    active.current=selected; setHistory(null);setReply('');requestId.current=''; if(!selected)return;
    let cancelled=false;
    const refresh=()=>request<History>(`/whatsapp/conversations/${selected}`,{cache:'no-store'}).then(v=>{if(!cancelled)setHistory(v)}).catch(e=>{if(!cancelled)setError(e.message)});
    void refresh();const timer=setInterval(()=>{void refresh()},5000);return()=>{cancelled=true;clearInterval(timer)};
  },[request,selected]);
  async function save(e: FormEvent) {
    e.preventDefault(); if(!settings)return;setBusy(true);setError('');setNotice('');
    try{setSettings(await request<Settings>('/whatsapp/settings',{method:'PATCH',body:JSON.stringify({enabled:settings.enabled,greeting:settings.greeting,deliveryText:settings.deliveryText,handoffText:settings.handoffText})}));setNotice('Configurações salvas.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setBusy(false)}
  }
  async function send(e: FormEvent) {
    e.preventDefault();if(!reply.trim()||!selected||busy)return;const cid=selected;setBusy(true);setError('');setNotice('');
    if(!requestId.current)requestId.current=crypto.randomUUID();
    try{await request(`/whatsapp/conversations/${cid}/messages`,{method:'POST',body:JSON.stringify({text:reply,requestId:requestId.current})});if(active.current===cid){setReply('');requestId.current='';const result=await request<History>(`/whatsapp/conversations/${cid}`,{cache:'no-store'});if(active.current===cid)setHistory(result);}await loadList();}catch(e){setError(e instanceof Error?e.message:'Não foi possível enviar.')}finally{setBusy(false)}
  }
  async function mode(human:boolean) {
    const cid=selected;setBusy(true);setError('');try{await request(`/whatsapp/conversations/${cid}`,{method:'PATCH',body:JSON.stringify({human})});const result=await request<History>(`/whatsapp/conversations/${cid}`,{cache:'no-store'});if(active.current===cid)setHistory(result);await loadList();}catch(e){setError(e instanceof Error?e.message:'Falha ao alterar atendimento.')}finally{setBusy(false)}
  }
  return <div className="mx-auto max-w-6xl space-y-5">
    <header className="rounded-3xl bg-emerald-950 p-6 text-white sm:p-8"><p className="text-xs font-bold uppercase tracking-widest text-emerald-300">Atendimento da sua loja</p><h1 className="mt-2 text-3xl font-black">WhatsApp</h1><p className="mt-2 max-w-2xl text-sm text-emerald-100">Seu cardápio e as informações da loja, disponíveis na conversa com o cliente.</p><span className="mt-4 inline-block rounded-full bg-white/10 px-3 py-1 text-sm">{settings ? settings.connected ? `${settings.displayPhone} · ${settings.enabled?'Automático ativado':'Automático pausado'}` : 'Aguardando conexão do número' : 'Carregando conexão…'}</span></header>
    {error&&<div role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}<button onClick={()=>setError('')} className="ml-3 underline">Fechar</button></div>}
    {notice&&<p role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-800">{notice}</p>}
    {settings&&!settings.connected&&<p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm">Solicite ao administrador a conexão do WhatsApp da sua loja. Após conectar, ative o atendimento em “Respostas automáticas”.</p>}
    {settings&&!settings.serverReady&&<p className="rounded-xl bg-amber-50 p-4 text-sm">A configuração do WhatsApp no servidor ainda precisa ser concluída pelo administrador.</p>}
    <nav aria-label="Área do WhatsApp" className="flex gap-2"><button onClick={()=>setTab('inbox')} className={`rounded-xl px-4 py-3 font-bold ${tab==='inbox'?'bg-emerald-700 text-white':'bg-white'}`}>Conversas {list.filter(c=>c.human).length>0&&`(${list.filter(c=>c.human).length})`}</button><button onClick={()=>setTab('settings')} className={`rounded-xl px-4 py-3 font-bold ${tab==='settings'?'bg-emerald-700 text-white':'bg-white'}`}>Respostas automáticas</button></nav>
    {tab==='settings'&&settings&&<form onSubmit={save} className="grid gap-6 rounded-3xl border border-stone-200 bg-white p-5 sm:p-7 lg:grid-cols-2"><div className="space-y-5">
      <label className="flex items-center gap-3 font-bold"><input type="checkbox" checked={settings.enabled} disabled={!settings.connected||!settings.serverReady} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/>Ativar atendimento automático</label>
      <label className="block text-sm font-bold">Saudação<textarea className={field} rows={3} maxLength={700} placeholder="Olá! Bem-vindo(a) à nossa loja." value={settings.greeting} onChange={e=>setSettings({...settings,greeting:e.target.value})}/></label>
      <label className="block text-sm font-bold">Informações adicionais sobre entrega<textarea className={field} rows={3} maxLength={700} placeholder="Ex.: entregamos nos bairros atendidos no cardápio." value={settings.deliveryText} onChange={e=>setSettings({...settings,deliveryText:e.target.value})}/></label>
      <label className="block text-sm font-bold">Mensagem ao chamar um atendente<textarea className={field} rows={3} maxLength={700} placeholder="Sua conversa está aguardando atendimento da loja." value={settings.handoffText} onChange={e=>setSettings({...settings,handoffText:e.target.value})}/></label>
      <button disabled={busy||!settings.connected} className={button}>{busy?'Salvando…':'Salvar configurações'}</button>
    </div><aside className="rounded-2xl bg-stone-50 p-5"><h2 className="font-black">Como o cliente será atendido</h2><ol className="mt-4 space-y-3 text-sm"><li>1. Cardápio — link da sua loja.</li><li>2. Horários e endereço — dados do seu cadastro.</li><li>3. Entrega e retirada — opções habilitadas na loja.</li><li>4. Falar com a loja — pausa o robô nesta conversa.</li></ol><p className="mt-5 break-all text-sm text-emerald-800">{settings.menuUrl||'Link disponível após configuração do servidor.'}</p><p className="mt-5 text-sm text-stone-600">O cliente pode escrever MENU para voltar ao automático ou SAIR para pausar as respostas. Ao assumir uma conversa, responda na aba Conversas.</p><p className="mt-3 text-sm text-stone-600">Campos vazios usam as mensagens padrão. Áudios e imagens são encaminhados ao atendimento humano; esta versão exibe apenas um aviso desses anexos.</p></aside></form>}
    {tab==='inbox'&&<section className="grid overflow-hidden rounded-3xl border border-stone-200 bg-white lg:grid-cols-[300px_1fr]">
      <aside className="max-h-[580px] overflow-y-auto border-b border-stone-200 lg:border-b-0 lg:border-r"><div className="border-b p-4"><h2 className="font-black">Conversas recentes</h2><p className="text-xs text-stone-500">Até 100 conversas · atualização automática</p></div>{!list.length?<p className="p-5 text-sm text-stone-500">As mensagens recebidas aparecerão aqui depois que o número e o recebimento de mensagens forem configurados.</p>:list.map(c=><button key={c._id} onClick={()=>setSelected(c._id)} className={`block w-full border-b p-4 text-left ${selected===c._id?'bg-emerald-50':'hover:bg-stone-50'}`}><strong className="block truncate">{c.customerName||c.customerPhone}</strong><span className="text-xs text-stone-500">{c.customerPhone}</span><p className="mt-1 truncate text-sm text-stone-600">{c.lastText}</p><span className="mt-2 inline-block rounded-full bg-stone-100 px-2 py-1 text-xs">{c.optedOut?'Cliente pausou':c.human?'Atendimento humano':'Automático'}</span></button>)}</aside>
      <div className="flex min-h-[520px] flex-col">{!selected?<div className="m-auto p-8 text-center text-stone-500">Selecione uma conversa para acompanhar ou responder.</div>:!history?<p className="p-5">Carregando conversa…</p>:<><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h2 className="font-black">{history.conversation.customerName||history.conversation.customerPhone}</h2><p className="text-xs text-stone-500">{history.conversation.customerPhone}</p></div><button disabled={busy||history.conversation.optedOut} onClick={()=>void mode(!history.conversation.human)} className="rounded-xl border border-stone-300 px-3 py-2 text-sm font-bold disabled:opacity-50">{history.conversation.human?'Devolver ao automático':'Assumir atendimento'}</button></div>
      <div aria-live="polite" className="flex max-h-[420px] flex-1 flex-col gap-3 overflow-y-auto bg-stone-50 p-4">{history.messages.map(m=><article key={m._id} className={`max-w-[90%] rounded-2xl p-3 text-sm sm:max-w-[80%] ${m.direction==='OUT'?'self-end bg-emerald-100':'self-start border bg-white'}`}><p className="whitespace-pre-wrap break-words">{m.text}</p><p className="mt-2 text-[11px] text-stone-500">{new Date(m.createdAt).toLocaleString('pt-BR')} · {statusLabels[m.status]||m.status}</p>{m.error&&<p className="mt-1 text-xs text-red-700">{m.error}</p>}</article>)}</div>
      <form onSubmit={send} className="border-t p-4">{!history.canReply&&<p className="mb-2 text-sm text-amber-800">{history.conversation.optedOut?'O cliente pausou as mensagens. Aguarde ele enviar MENU.':'A janela de 24 horas encerrou. Aguarde uma nova mensagem do cliente.'}</p>}<label className="sr-only" htmlFor="whatsapp-reply">Sua resposta</label><textarea id="whatsapp-reply" rows={2} maxLength={4000} className={field} value={reply} disabled={busy||!history.canReply||!settings?.connected} onChange={e=>{setReply(e.target.value);requestId.current=''}} placeholder="Digite sua resposta…"/><div className="mt-2 flex items-center justify-between gap-3"><p className="text-xs text-stone-500">Responder pausa o robô. Histórico de mensagens por 30 dias.</p><button className={button} disabled={busy||!history.canReply||!reply.trim()||!settings?.connected}>{busy?'Enviando…':'Enviar'}</button></div></form></>}</div>
    </section>}
  </div>;
}
