'use client';
import Link from 'next/link'; import { useEffect, useRef, useState } from 'react'; import { useRouter } from 'next/navigation';
import { useAuth } from '../AuthProvider'; import type { City } from '../../lib/public-restaurants'; import type { Role } from '../../lib/auth'; import { CitySelector } from './CitySelector'; import { SearchBar } from './SearchBar';
const links: Record<Role, Array<{ label: string; href: string }>> = {
  CUSTOMER: [{ label: 'Minha conta', href: '/cliente#conta' }, { label: 'Meus pedidos', href: '/cliente' }, { label: 'Meus endereços', href: '/cliente#enderecos' }],
  RESTAURANT_ADMIN: [{ label: 'Minha conta', href: '/empresa#conta' }, { label: 'Painel da loja', href: '/empresa' }, { label: 'Pedidos e catálogo', href: '/empresa#operacao' }, { label: 'Funcionários e configurações', href: '/empresa#configuracoes' }],
  EMPLOYEE: [{ label: 'Minha conta', href: '/funcionario#conta' }, { label: 'Painel do funcionário', href: '/funcionario' }, { label: 'Pedidos permitidos', href: '/funcionario#pedidos' }],
  SUPER_ADMIN: [{ label: 'Minha conta', href: '/admin#conta' }, { label: 'Painel administrativo', href: '/admin' }, { label: 'Estabelecimentos', href: '/admin/restaurantes' }],
};
export function Header(props: { cities: City[]; city: string; onCityChange: (value: string) => void; search: string; onSearchChange: (value: string) => void }) {
  const { user, loading, logout } = useAuth(); const router = useRouter(); const [open, setOpen] = useState(false); const menu = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (event: MouseEvent) => { if (!menu.current?.contains(event.target as Node)) setOpen(false); }; const keyboard = (event: KeyboardEvent) => { if (event.key === 'Escape') setOpen(false); }; document.addEventListener('mousedown', close); document.addEventListener('keydown', keyboard); return () => { document.removeEventListener('mousedown', close); document.removeEventListener('keydown', keyboard); }; }, []);
  return <header className="border-b border-stone-200 bg-[#fbfcf8]"><div className="mx-auto max-w-7xl px-4 py-5 sm:px-6"><div className="flex items-center justify-between gap-4"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-ink text-lg font-black text-lime">M</span><span><b className="block text-base tracking-[.14em] text-ink">MENU FLOW</b><small className="hidden text-stone-500 sm:block">Sua cidade, muitas escolhas</small></span></Link>{loading ? <span aria-label="Verificando sessão" className="h-11 w-28 animate-pulse rounded-xl bg-stone-200" /> : user ? <div className="relative" ref={menu}><button type="button" aria-haspopup="menu" aria-expanded={open} onClick={() => setOpen(!open)} className="flex items-center gap-2 rounded-xl bg-ink px-4 py-3 text-sm font-black text-white"><span aria-hidden>👤</span><span className="max-w-28 truncate">{user.name.split(' ')[0]}</span><span aria-hidden>⌄</span></button>{open && <div role="menu" className="absolute right-0 z-30 mt-2 w-64 rounded-2xl border bg-white p-2 shadow-soft">{links[user.role].map((item) => <Link role="menuitem" key={item.label} href={item.href} onClick={() => setOpen(false)} className="block rounded-xl px-4 py-3 text-sm font-bold hover:bg-stone-100">{item.label}</Link>)}<button role="menuitem" className="w-full rounded-xl px-4 py-3 text-left text-sm font-bold text-red-700 hover:bg-red-50" onClick={() => { logout(); setOpen(false); router.replace('/'); }}>Sair</button></div>}</div> : <Link className="rounded-xl bg-ink px-5 py-3 text-sm font-black text-white transition hover:-translate-y-0.5" href="/login?returnTo=/">Entrar</Link>}</div><div className="mt-5 grid gap-3 md:grid-cols-[minmax(220px,.65fr)_1.35fr]"><CitySelector cities={props.cities} value={props.city} onChange={props.onCityChange} /><SearchBar value={props.search} onChange={props.onSearchChange} /></div></div></header>;
}
