'use client';
import { useEffect, useState } from 'react'; import { HomeBannerCarousel, type PublicHomeBanner } from '../components/home/HomeBannerCarousel'; import { Header } from '../components/home/Header'; import { RestaurantGrid, RestaurantGridSkeleton } from '../components/restaurants/RestaurantGrid'; import { apiUrl } from '../lib/api'; import type { City, EstablishmentTypeOption, RestaurantPage } from '../lib/public-restaurants';
const CITY_KEY = 'menu-flow.selected-city';
export default function HomePage() {
  const [cities, setCities] = useState<City[]>([]); const [types,setTypes]=useState<EstablishmentTypeOption[]>([]); const [banners,setBanners]=useState<PublicHomeBanner[]>([]); const [city, setCity] = useState(''); const [search, setSearch] = useState(''); const [debouncedSearch, setDebouncedSearch] = useState(''); const [type, setType] = useState(''); const [result, setResult] = useState<RestaurantPage>(); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [openOnly, setOpenOnly] = useState(false); const [page, setPage] = useState(1); const [statusRefresh, setStatusRefresh] = useState(0);
  useEffect(() => { setCity(localStorage.getItem(CITY_KEY) || ''); void fetch(apiUrl('/public/home-banners'), { cache: 'no-store' }).then(response => response.ok ? response.json() : Promise.reject()).then(data => setBanners(data as PublicHomeBanner[])).catch(() => setBanners([])); void Promise.all([fetch(apiUrl('/public/cities')), fetch(apiUrl('/public/establishment-types'))]).then(async ([citiesResponse, typesResponse]) => { if (!citiesResponse.ok || !typesResponse.ok) throw new Error(); setCities(await citiesResponse.json() as City[]); setTypes(await typesResponse.json() as EstablishmentTypeOption[]); }).catch(() => setError('Não foi possível carregar os filtros agora.')); }, []);
  useEffect(() => { const timer = window.setTimeout(() => { setDebouncedSearch(search); setPage(1); }, 350); return () => window.clearTimeout(timer); }, [search]);
  useEffect(() => { const timer = window.setInterval(() => setStatusRefresh((value) => value + 1), 60_000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { const controller = new AbortController(); const params = new URLSearchParams({ page: String(page), limit: '12' }); const [selectedCity, state] = city.split('|'); if (selectedCity) params.set('city', selectedCity); if (state) params.set('state', state); if (debouncedSearch) params.set('search', debouncedSearch); if (openOnly) params.set('open', 'true'); if (type) params.set('type', type); setLoading(true); setError(''); void fetch(apiUrl(`/public/establishments?${params}`), { signal: controller.signal, cache: 'no-store' }).then(async (response) => { if (!response.ok) throw new Error(); setResult(await response.json() as RestaurantPage); }).catch((cause: unknown) => { if ((cause as { name?: string }).name !== 'AbortError') setError('Não foi possível carregar os estabelecimentos. Tente novamente.'); }).finally(() => setLoading(false)); return () => controller.abort(); }, [city, debouncedSearch, openOnly, type, page, statusRefresh]);
  function selectCity(value: string) { setCity(value); setPage(1); if (value) localStorage.setItem(CITY_KEY, value); else localStorage.removeItem(CITY_KEY); }
  const selectedName = city.split('|')[0];
  const selectedType = types.find((item) => item.slug === type);
  const heading = selectedType
    ? selectedName ? `Estabelecimentos de ${selectedType.name} em ${selectedName}` : `Estabelecimentos: ${selectedType.name}`
    : selectedName ? `Estabelecimentos em ${selectedName}` : 'Todos os estabelecimentos';
  return <main className="min-h-screen bg-background"><Header cities={cities} city={city} onCityChange={selectCity} search={search} onSearchChange={setSearch} /><HomeBannerCarousel banners={banners}/><section className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div className="mb-5 flex flex-wrap gap-2" aria-label="Filtrar por tipo">{[{id:'all',name:'Todos',slug:''},...types].map((option) => <button key={option.id} onClick={() => { setType(option.slug); setPage(1); }} aria-pressed={type === option.slug} className={`rounded-full border px-4 py-2 text-sm font-bold ${type === option.slug ? 'border-ink bg-ink text-white' : 'bg-surface text-stone-700'}`}>{option.name}</button>)}</div><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-black uppercase tracking-[.15em] text-accent">Explore perto de você</p><h2 className="mt-2 text-3xl font-black text-ink">{heading}</h2>{result && <p className="mt-2 text-sm text-stone-500">{result.pagination.total} {result.pagination.total === 1 ? 'estabelecimento encontrado' : 'estabelecimentos encontrados'}</p>}</div><label className="flex cursor-pointer items-center gap-3 rounded-2xl border bg-surface px-4 py-3 text-sm font-bold"><input type="checkbox" checked={openOnly} onChange={(event) => { setOpenOnly(event.target.checked); setPage(1); }} className="accent-primary" /> Abertos agora</label></div>{error ? <div role="alert" className="rounded-3xl border border-danger/30 bg-danger/10 p-8 text-center text-danger"><b>Algo não saiu como esperado.</b><p className="mt-2">{error}</p></div> : loading ? <RestaurantGridSkeleton /> : result?.items.length ? <><RestaurantGrid restaurants={result.items} />{result.pagination.pages > 1 && <nav className="mt-8 flex items-center justify-center gap-4"><button disabled={page === 1} onClick={() => setPage((value) => value - 1)} className="rounded-xl border bg-surface px-5 py-3 font-bold disabled:opacity-40">Anterior</button><span className="text-sm text-stone-500">Página {page} de {result.pagination.pages}</span><button disabled={page === result.pagination.pages} onClick={() => setPage((value) => value + 1)} className="rounded-xl bg-ink px-5 py-3 font-bold text-white disabled:opacity-40">Próxima</button></nav>}</> : <div className="rounded-3xl border border-dashed border-stone-300 bg-surface p-10 text-center"><span className="text-4xl">🏪</span><h3 className="mt-4 text-xl font-black">Nenhum estabelecimento encontrado</h3><p className="mt-2 text-stone-500">Tente outra busca, cidade ou remova algum filtro.</p></div>}</section><footer className="border-t bg-surface px-4 py-8 text-center text-sm text-stone-500"><b className="text-ink">MENU FLOW</b> · Estabelecimentos e produtos em um só lugar.</footer></main>;
}
