'use client';
import Link from 'next/link'; import { usePathname, useRouter } from 'next/navigation'; import { useEffect, useRef, useState } from 'react';
import { roleLabel } from '../../lib/auth'; import { useAuth } from '../AuthProvider'; import { useEmpresa } from './EmpresaContext';
const titles: Record<string,string> = { '/empresa': 'Visão geral', '/empresa/pedidos': 'Pedidos', '/empresa/cardapio': 'Cardápio / Produtos', '/empresa/categorias': 'Categorias', '/empresa/funcionarios': 'Funcionários', '/empresa/dados': 'Dados da empresa', '/empresa/configuracoes': 'Configurações', '/empresa/conta': 'Minha conta' };
export function EmpresaHeader({ toggle, menuOpen }: { toggle: () => void; menuOpen: boolean }) {
 const pathname=usePathname(); const router=useRouter(); const {user,logout}=useAuth(); const {establishment}=useEmpresa(); const [open,setOpen]=useState(false); const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const click=(e:MouseEvent)=>{if(!ref.current?.contains(e.target as Node))setOpen(false)}; const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)}; document.addEventListener('mousedown',click);document.addEventListener('keydown',key);return()=>{document.removeEventListener('mousedown',click);document.removeEventListener('keydown',key)}},[]);
 if(!user)return null; const initial=user.name.trim().charAt(0).toUpperCase();
 return <header className="sticky top-0 z-30 flex min-h-20 items-center justify-between gap-3 border-b border-stone-200 bg-white/95 px-4 backdrop-blur sm:px-7"><div className="flex min-w-0 items-center gap-3"><button type="button" aria-label={menuOpen?'Fechar menu':'Abrir menu'} aria-expanded={menuOpen} onClick={toggle} className="grid h-11 w-11 place-items-center rounded-xl border lg:hidden">☰</button><div><p className="text-xs font-bold uppercase tracking-widest text-stone-400">Painel da empresa</p><h1 className="truncate text-xl font-black sm:text-2xl">{titles[pathname] || 'Painel da empresa'}</h1></div></div><div className="relative" ref={ref}><button type="button" aria-haspopup="menu" aria-expanded={open} onClick={()=>setOpen(!open)} className="flex items-center gap-3 rounded-xl p-2 text-left hover:bg-stone-100"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-ink font-black text-lime">{initial}</span><span className="hidden max-w-52 sm:block"><strong className="block truncate text-sm">{user.name}</strong><small className="block truncate text-stone-500">{roleLabel[user.role]}{establishment && ` · ${establishment.tradeName || establishment.name}`}</small></span><span aria-hidden className="hidden sm:block">⌄</span></button>{open&&<div role="menu" className="absolute right-0 mt-2 w-56 rounded-2xl border bg-white p-2 shadow-soft"><Link role="menuitem" href="/empresa/conta" onClick={()=>setOpen(false)} className="block rounded-xl px-4 py-3 text-sm font-bold hover:bg-stone-100">Minha conta</Link>{establishment?.slug&&<a role="menuitem" href={`/${establishment.slug}`} target="_blank" rel="noreferrer" className="block rounded-xl px-4 py-3 text-sm font-bold hover:bg-stone-100">Ver loja</a>}<button role="menuitem" onClick={()=>{logout();router.replace('/')}} className="w-full rounded-xl px-4 py-3 text-left text-sm font-bold text-red-700 hover:bg-red-50">Sair</button></div>}</div></header>;
}
