'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '../../../components/AuthProvider';
import { safeReturnTo } from '../../../lib/auth';
import { apiUrl } from '../../../lib/api';
import { PasswordField } from '../../../components/auth/PasswordField';
import { BrandLogo } from '../../../components/BrandLogo';

export default function CustomerLoginPage() { const router = useRouter(); const { login } = useAuth(); const [register, setRegister] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setLoading(true); setError(''); const endpoint = register ? '/auth/customer/register' : '/auth/login'; const payload = Object.fromEntries(form); try { const response = await fetch(apiUrl(endpoint), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json().catch(() => null) as { accessToken?: string; user?: { id: string; name: string; email: string; phone?: string; role: 'CUSTOMER' }; message?: string }; if (!response.ok) throw new Error(data?.message ?? 'Não foi possível continuar.'); if (register) { setRegister(false); setError('Conta criada. Entre com suas credenciais.'); return; } if (!data?.accessToken || data.user?.role !== 'CUSTOMER') throw new Error('Esta conta não é uma conta de cliente.'); login({ accessToken: data.accessToken, user: data.user }); const requestedReturn = new URLSearchParams(window.location.search).get('returnTo'); router.replace(requestedReturn ? safeReturnTo(requestedReturn) : '/cliente'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Erro inesperado.'); } finally { setLoading(false); } }
  return <main className="flex min-h-screen items-center justify-center p-5"><form onSubmit={submit} className="w-full max-w-md border border-border rounded-3xl bg-surface p-7 shadow-soft"><BrandLogo priority className="mx-auto w-[clamp(9rem,45vw,13rem)] rounded-2xl" /><h1 className="mt-3 text-3xl font-black">{register ? 'Crie sua conta' : 'Minha conta'}</h1>{register && <><input className="field" required name="name" placeholder="Seu nome" /><input className="field" required name="phone" placeholder="Telefone" /></>}<input className="field" required name="email" type="email" placeholder="E-mail" /><PasswordField required name="password" autoComplete={register ? 'new-password' : 'current-password'} minLength={8} placeholder="Senha (mínimo 8 caracteres)" />{error && <p className="mt-4 text-sm text-danger">{error}</p>}<button disabled={loading} className="mt-6 w-full rounded-xl bg-ink py-4 font-black text-white">{loading ? 'AGUARDE…' : register ? 'CRIAR CONTA' : 'ENTRAR'}</button><button type="button" onClick={() => { setRegister(!register); setError(''); }} className="mt-4 w-full text-sm font-bold underline">{register ? 'Já tenho uma conta' : 'Ainda não tenho uma conta'}</button></form></main>; }
