'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { useDashboard } from '../../../components/dashboard/DashboardContext';
import { API_BASE_URL } from '../../../lib/api';
type Store = { restaurantId: string; name: string; connected: boolean; enabled: boolean; displayPhone: string; phoneNumberId: string; lastError: string; lastReceivedAt?: string };
type Result = { ready: boolean; missing: string[]; stores: Store[] };
export default function AdminWhatsapp() {
  const {request}=useDashboard();const [data,setData]=useState<Result|null>(null);const [id,setId]=useState('');const [phone,setPhone]=useState('');const [token,setToken]=useState('');const [search,setSearch]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const load=useCallback(async()=>{setData(await request<Result>('/whatsapp/admin/stores',{cache:'no-store'}))},[request]);
  useEffect(()=>{void load().catch(e=>setError(e.message))},[load]);
  const store=data?.stores.find(s=>s.restaurantId===id);
  async function connect(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{await request(`/whatsapp/admin/stores/${id}/connection`,{method:'POST',body:JSON.stringify({phoneNumberId:phone.trim(),accessToken:token.trim()})});setToken('');setNotice('Credenciais validadas. Confirme a assinatura do webhook na Meta; depois o lojista pode ativar o robô.');await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao conectar.')}finally{setBusy(false)}}
  async function disconnect(){if(!confirm('Desconectar este número do Menu Flow e cancelar mensagens que ainda estão na fila?'))return;setBusy(true);setError('');setNotice('');try{await request(`/whatsapp/admin/stores/${id}/connection`,{method:'DELETE'});setToken('');setPhone('');await load();setNotice('Número desconectado do Menu Flow.')}catch(e){setError(e instanceof Error?e.message:'Falha ao desconectar.')}finally{setBusy(false)}}
  return <div className="mx-auto max-w-5xl space-y-5"><header className="rounded-3xl bg-emerald-950 p-7 text-white"><p className="text-xs font-bold uppercase tracking-widest text-emerald-300">Integrações oficiais</p><h1 className="mt-2 text-3xl font-black">WhatsApp por estabelecimento</h1><p className="mt-2 text-sm text-emerald-100">Conecte um número de WhatsApp a cada loja. O lojista configura o autoatendimento no próprio painel.</p></header>
    {error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-800">{notice}</p>}
    {data&&!data.ready&&<div className="rounded-xl bg-amber-50 p-4 text-sm"><strong>Configuração do servidor pendente</strong><ul className="mt-2 list-inside list-disc">{data.missing.map(v=><li key={v}>{v}</li>)}</ul><p className="mt-2">Consulte o guia WHATSAPP-AUTOATENDIMENTO.md incluído no projeto.</p></div>}
    <section className="rounded-2xl border bg-white p-5 text-sm"><h2 className="font-black">Recebimento de mensagens</h2><p className="mt-2">No aplicativo da Meta, configure o endereço abaixo e assine o campo <b>messages</b>. A conta WhatsApp Business de cada loja também precisa estar inscrita nesse aplicativo.</p><code className="mt-3 block break-all rounded-xl bg-stone-100 p-3">{API_BASE_URL}/whatsapp/webhook</code><p className="mt-2 text-stone-600">O token de verificação é o configurado no servidor. Validar as credenciais abaixo não conclui a assinatura do webhook.</p></section>
    <div className="grid gap-5 md:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><label htmlFor="store-search" className="text-sm font-bold">Encontrar estabelecimento</label><input id="store-search" className="mt-2 w-full rounded-xl border p-3" placeholder="Nome da loja" value={search} onChange={e=>setSearch(e.target.value)}/><div className="mt-3 max-h-[450px] space-y-2 overflow-y-auto">{data?.stores.filter(s=>s.name.toLowerCase().includes(search.toLowerCase())).map(s=><button disabled={busy} key={s.restaurantId} onClick={()=>{setId(s.restaurantId);setPhone(s.phoneNumberId);setToken('');setNotice('');setError('')}} className={`block w-full rounded-xl border p-3 text-left ${id===s.restaurantId?'border-emerald-700 bg-emerald-50':''}`}><strong className="block">{s.name}</strong><span className="text-xs text-stone-600">{s.connected?`${s.displayPhone} · ${s.enabled?'Automático ativo':'Automático pausado'}`:'Sem conexão'}</span></button>)}{!data&&<p>Carregando lojas…</p>}</div></section>
    <section className="rounded-2xl border bg-white p-5">{store?<form onSubmit={connect} className="space-y-4"><h2 className="text-xl font-black">{store.name}</h2><p className="text-sm text-stone-600">Cadastre as credenciais autorizadas para o número desta loja. O token é protegido no servidor e não é exibido ao lojista.</p><label className="block text-sm font-bold">ID do número de telefone (Phone Number ID)<input required pattern="[0-9]{5,30}" readOnly={store.connected} className="mt-1 w-full rounded-xl border p-3 font-normal" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="block text-sm font-bold">Token de acesso da Meta<input required type="password" autoComplete="new-password" minLength={20} maxLength={4096} className="mt-1 w-full rounded-xl border p-3 font-normal" value={token} onChange={e=>setToken(e.target.value)}/></label><p className="text-xs text-stone-500">Use um token de sistema com acesso ao número e às permissões necessárias. Tokens temporários expiram.</p><button disabled={busy||!data?.ready} className="rounded-xl bg-emerald-700 px-4 py-3 font-bold text-white disabled:opacity-50">{busy?'Processando…':store.connected?'Validar e atualizar token':'Validar e conectar'}</button>{store.connected&&<button type="button" disabled={busy} onClick={()=>void disconnect()} className="ml-3 rounded-xl border px-3 py-3 text-red-700 disabled:opacity-50">Desconectar</button>}{store.lastReceivedAt&&<p className="text-sm">Última mensagem recebida: {new Date(store.lastReceivedAt).toLocaleString('pt-BR')}</p>}{store.lastError&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-800">Última falha: {store.lastError}</p>}</form>:<p className="text-stone-500">Selecione uma loja para configurar o número.</p>}</section></div>
  </div>;
}
