'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { authenticatedRequest } from '../../../lib/authenticated-request';

const safeTargetUrl = (value:string) => !value.trim() || (/^\/(?!\/)/.test(value.trim()) && !/[\\\r\n]/.test(value.trim())) || /^https:\/\/[^\s]+$/i.test(value.trim());
type Banner={_id:string;id?:string;name:string;title?:string;description?:string;desktopImageUrl:string;mobileImageUrl:string;targetUrl?:string;active:boolean;sortOrder:number};
type Form={name:string;title:string;description:string;desktopImageUrl:string;mobileImageUrl:string;targetUrl:string;active:boolean;sortOrder:number};
const empty:Form={name:'',title:'',description:'',desktopImageUrl:'',mobileImageUrl:'',targetUrl:'',active:true,sortOrder:0};
function Preview({url,mobile}:{url:string;mobile?:boolean}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[url]);if(!url)return <div className={`grid place-items-center rounded-xl border border-dashed bg-background text-sm text-stone-500 ${mobile?'aspect-[4/5] max-w-52':'aspect-[3/1] w-full'}`}>A prévia aparecerá aqui.</div>;return failed?<p role="alert" className="rounded-xl bg-danger/10 p-3 text-sm text-danger">Não foi possível carregar esta imagem.</p>:<img src={url} onError={()=>setFailed(true)} alt={mobile?'Prévia para celular':'Prévia para computador'} className={`rounded-xl border object-cover ${mobile?'aspect-[4/5] w-52':'aspect-[3/1] w-full'}`}/>}
export default function BannersPage(){
 const [items,setItems]=useState<Banner[]>([]),[form,setForm]=useState<Form>(empty);const [open,setOpen]=useState(false),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[deleting,setDeleting]=useState<Banner|null>(null);
 const load=useCallback(()=>{setLoading(true);return authenticatedRequest<Banner[]>('/admin/home-banners').then(setItems).catch(()=>setError('Não foi possível carregar os banners. Tente novamente.')).finally(()=>setLoading(false))},[]);useEffect(()=>{void load()},[load]);
 const begin=(item?:Banner)=>{setEditing(item?._id||null);setForm(item?{name:item.name,title:item.title||'',description:item.description||'',desktopImageUrl:item.desktopImageUrl,mobileImageUrl:item.mobileImageUrl,targetUrl:item.targetUrl||'',active:item.active,sortOrder:item.sortOrder}:empty);setError('');setOpen(true)};
 async function save(event:FormEvent){event.preventDefault();if(busy)return;if(!safeTargetUrl(form.targetUrl)){setError('Informe um caminho interno ou uma URL segura iniciada por https://.');return}setBusy(true);setError('');try{await authenticatedRequest(editing?`/admin/home-banners/${editing}`:'/admin/home-banners',{method:editing?'PATCH':'POST',body:JSON.stringify(form)});setOpen(false);await load()}catch(error){setError(error instanceof Error?error.message:'Não foi possível salvar o banner. Tente novamente.')}finally{setBusy(false)}}
 async function update(item:Banner,changes:Partial<Banner>){try{await authenticatedRequest(`/admin/home-banners/${item._id}`,{method:'PATCH',body:JSON.stringify(changes)});await load()}catch{setError('Não foi possível atualizar o banner. Tente novamente.')}}
 async function remove(){if(!deleting||busy)return;setBusy(true);try{await authenticatedRequest(`/admin/home-banners/${deleting._id}`,{method:'DELETE'});setDeleting(null);await load()}catch{setError('Não foi possível excluir o banner. Tente novamente.')}finally{setBusy(false)}}
 return <section className="mx-auto max-w-6xl"><header className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-black">Banners da tela inicial</h1><p className="mt-1 text-stone-500">Gerencie as imagens promocionais exibidas na página inicial do Menu Flow.</p></div><button onClick={()=>begin()} className="rounded-xl bg-ink px-5 py-3 font-bold text-white">+ Adicionar banner</button></header>{error&&<p role="alert" className="mt-5 rounded-xl bg-danger/10 p-3 text-danger">{error}</p>}{loading?<div className="mt-7 h-40 animate-pulse rounded-2xl bg-stone-200"/>:items.length?<div className="mt-7 grid gap-5">{items.map((item,index)=><article key={item._id} className="rounded-2xl bg-surface p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-black">{item.name}</h2><p className="text-sm text-stone-500">Posição: {item.sortOrder} · <span className={item.active?'text-green-700':'text-stone-500'}>{item.active?'Ativo':'Inativo'}</span></p><p className="mt-1 text-sm text-stone-500"><b>Destino:</b> {item.targetUrl||'Nenhum'}</p></div><div className="flex flex-wrap gap-2"><button disabled={index===0} onClick={()=>void update(item,{sortOrder:Math.max(0,(items[index-1]?.sortOrder??item.sortOrder)-1)})} className="rounded-lg border px-3 py-2 disabled:opacity-30" aria-label="Mover para cima">↑</button><button disabled={index===items.length-1} onClick={()=>void update(item,{sortOrder:(items[index+1]?.sortOrder??item.sortOrder)+1})} className="rounded-lg border px-3 py-2 disabled:opacity-30" aria-label="Mover para baixo">↓</button><button onClick={()=>begin(item)} className="rounded-lg border px-3 py-2 font-bold">Editar</button><button onClick={()=>void update(item,{active:!item.active})} className="rounded-lg border px-3 py-2 font-bold">{item.active?'Desativar':'Ativar'}</button><button onClick={()=>setDeleting(item)} className="rounded-lg bg-danger/10 px-3 py-2 font-bold text-danger">Excluir</button></div></div><div className="mt-4 grid gap-4 md:grid-cols-[3fr_1fr]"><Preview url={item.desktopImageUrl}/><Preview url={item.mobileImageUrl} mobile/></div></article>)}</div>:<div className="mt-7 rounded-2xl border border-dashed bg-surface p-10 text-center"><h2 className="text-xl font-black">Nenhum banner cadastrado.</h2><p className="mt-2 text-stone-500">Adicione um banner para começar a divulgar campanhas na página inicial.</p><button onClick={()=>begin()} className="mt-5 rounded-xl bg-ink px-5 py-3 font-bold text-white">Adicionar banner</button></div>}
 {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-ink/60 p-3 sm:p-5" role="dialog" aria-modal="true" aria-labelledby="banner-form-title"><form onSubmit={save} className="flex max-h-[94dvh] w-full max-w-6xl flex-col overflow-hidden rounded-3xl bg-surface shadow-soft sm:max-h-[90dvh]">
   <header className="sticky top-0 z-10 flex shrink-0 items-start justify-between gap-4 border-b bg-surface px-5 py-4 sm:px-7"><div><h2 id="banner-form-title" className="text-2xl font-black">{editing?'Editar banner':'Adicionar banner'}</h2><p className="mt-1 text-sm text-stone-500">Configure as imagens e o comportamento deste banner.</p></div><button type="button" disabled={busy} onClick={()=>setOpen(false)} aria-label="Fechar formulário" className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border font-bold disabled:opacity-50">✕</button></header>
   <div className="min-h-0 flex-1 overflow-y-auto px-5 py-5 sm:px-7">
    {error&&<p role="alert" className="mb-5 rounded-xl border border-danger/20 bg-danger/10 p-3 font-medium text-danger">{error}</p>}
    <div className="grid gap-5 lg:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]">
     <section className="rounded-2xl border bg-background/40 p-4 sm:p-5"><h3 className="text-xs font-black uppercase tracking-widest text-accent">Identificação</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="font-bold">Nome interno *<input required maxLength={120} className="field" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><small className="font-normal text-stone-500">Usado apenas na organização administrativa.</small></label><label className="font-bold">Título<input maxLength={160} className="field" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="font-bold md:col-span-2">Descrição<textarea maxLength={500} className="field min-h-20 resize-y" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div></section>
     <section className="rounded-2xl border bg-background/40 p-4 sm:p-5"><h3 className="text-xs font-black uppercase tracking-widest text-accent">Publicação</h3><label className="mt-4 block font-bold">Ordem de exibição<input required min="0" type="number" className="field" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:Number(e.target.value)})}/><small className="font-normal text-stone-500">Quanto menor o número, mais cedo o banner aparece.</small></label><label className="mt-4 flex items-center gap-3 rounded-xl border bg-surface p-3 font-bold"><input className="h-5 w-5 accent-primary" type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Exibir este banner</label></section>
    </div>
    <section className="mt-5 rounded-2xl border bg-background/40 p-4 sm:p-5"><h3 className="text-xs font-black uppercase tracking-widest text-accent">Imagens do banner</h3><div className="mt-4 grid gap-5 lg:grid-cols-2">
     <div className="min-w-0 rounded-2xl border bg-surface p-4"><label className="font-bold">Imagem para computador *<input required type="url" pattern="https://.*" placeholder="https://..." className="field" value={form.desktopImageUrl} onChange={e=>setForm({...form,desktopImageUrl:e.target.value})}/></label><p className="mt-2 text-sm text-stone-500">Tamanho recomendado: 1920 × 640 px · proporção 3:1.</p><p className="mb-2 mt-4 text-xs font-black uppercase text-stone-500">Prévia para computador</p><Preview url={form.desktopImageUrl}/></div>
     <div className="min-w-0 rounded-2xl border bg-surface p-4"><label className="font-bold">Imagem para celular *<input required type="url" pattern="https://.*" placeholder="https://..." className="field" value={form.mobileImageUrl} onChange={e=>setForm({...form,mobileImageUrl:e.target.value})}/></label><p className="mt-2 text-sm text-stone-500">Tamanho recomendado: 1080 × 1350 px · proporção 4:5.</p><p className="mb-2 mt-4 text-xs font-black uppercase text-stone-500">Prévia para celular</p><div className="flex justify-center"><Preview url={form.mobileImageUrl} mobile/></div></div>
    </div></section>
    <section className="mt-5 rounded-2xl border bg-background/40 p-4 sm:p-5"><h3 className="text-xs font-black uppercase tracking-widest text-accent">Ação do banner</h3><label className="mt-4 block font-bold">Link de redirecionamento<input type="text" inputMode="url" maxLength={2048} placeholder="/sabor-da-praca ou https://exemplo.com/promocao" className="field" value={form.targetUrl} onChange={e=>setForm({...form,targetUrl:e.target.value})}/><small className="font-normal text-stone-500">Opcional. Ao clicar no banner, o visitante será direcionado para este endereço.</small>{form.targetUrl.trim()&&<span className="mt-2 block break-all text-sm font-normal text-stone-600"><b>Destino:</b> {form.targetUrl.trim()}</span>}</label></section>
   </div>
   <footer className="sticky bottom-0 z-10 flex shrink-0 flex-col-reverse gap-3 border-t bg-surface px-5 py-4 sm:flex-row sm:justify-end sm:px-7"><button type="button" disabled={busy} onClick={()=>setOpen(false)} className="rounded-xl border px-5 py-3 font-bold disabled:opacity-50">Cancelar</button><button disabled={busy} className="rounded-xl bg-ink px-5 py-3 font-bold text-white disabled:opacity-50">{busy?'Salvando...':'Salvar banner'}</button></footer>
  </form></div>}
 {deleting&&<div className="fixed inset-0 z-50 grid place-items-center bg-ink/60 p-4" role="dialog" aria-modal="true" aria-labelledby="delete-title"><div className="max-w-md rounded-2xl bg-surface p-6"><h2 id="delete-title" className="text-2xl font-black">Excluir banner?</h2><p className="mt-3 text-stone-600">Tem certeza de que deseja excluir este banner? Esta ação não poderá ser desfeita.</p><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setDeleting(null)} className="rounded-xl border px-5 py-3 font-bold">Cancelar</button><button disabled={busy} onClick={()=>void remove()} className="rounded-xl bg-danger px-5 py-3 font-bold text-white">Excluir banner</button></div></div></div>}</section>;
}
